### ISSUE TITLE
Umbraco cloud

### ISSUE THREAD

**Issue by Matthew-Wise** [TeaCommerce/Tea-Commerce-for-Umbraco#82]
When adding tea commerce to an Umbraco Cloud, when syncing to another environment the install process of Tea Commerce installs its data types, unfortunately this results in cloud failing to import the data types as the UDI values don't match. (only done this from local -> live)

Cloud error:

Some artifacts collide on unique identifiers.
This means that they have different Udis, yet
they refer to the same unique Umbraco object
and therefore cannot be processed.
---------------------------------------------
Collisions for entity type "data-type": 
  Collisions for unique identifier "Tea Commerce: Store picker":
    UdaFile: ~/data/revision/data-type__4f17e9adc8e64e8484575756d46b5766.uda
    UdaFile: ~/data/revision/data-type__7cd2e8f0ec0f43c8a941bf1e19fcf300.uda
  Collisions for unique identifier "Tea Commerce: VAT group picker":
    UdaFile: ~/data/revision/data-type__b4402d6dd9dd41fba0ab6e84c63c2395.uda
    UdaFile: ~/data/revision/data-type__bdbfec3e2ea84703a7dd589974a5e193.uda
  Collisions for unique identifier "Tea Commerce: Variant Editor":
    UdaFile: ~/data/revision/data-type__54a555cf168a4784a3cb88221f78735b.uda
    UdaFile: ~/data/revision/data-type__f613a9de20fd4e5387e867a298b27566.uda
  Collisions for unique identifier "Tea Commerce: Stock management":
    UdaFile: ~/data/revision/data-type__657bb41c23dc44da8c473f12b0a6bb88.uda
    UdaFile: ~/data/revision/data-type__f9a01b7a5e61462dbb92e55fd05643e4.uda

Clouds resolution for this - https://our.umbraco.com/Documentation/Umbraco-Cloud/Troubleshooting/Deployments/Colliding-Datatypes/ in case it helps.

Thanks
Matt

**Comment by mattbrailsford** [comment]
Hi Matt,

Hmmm, that's an interesting one. The way I see it I think we have a couple of options

1) On install, install the property editors but don't setup the data types. This would make things a little hidden, but could probably be solved with good docs.
2) Look to see if we can install the data types with a fixed id. I think Umbraco might do this so it could be possible, but I'll need to look into it. But if we can do this, then the ID's would technically be the same on bother environments so shouldn't cause a problem.

**Comment by FransdeJong** [comment]
We ran into this issue to. 

I don't think the Id is going to solve anything because Cloud is looking for the name as a unique identifier.

Error message:
`  Collisions for unique identifier "Tea Commerce: Variant Editor":`

Uda file:
`{
  "EditorAlias": "TeaCommerce.VariantEditor",
  "DatabaseType": 2,
  "PreValues": {},
  "Parent": null,
  "Udi": "umb://data-type/9ace2204146a4625ba7f5c8337961499",
  "Dependencies": [],
  **"Name": "Tea Commerce: Variant Editor",**
  "Alias": null,
  "__type": "Umbraco.Deploy,Umbraco.Deploy.Artifacts.DataTypeArtifact",
  "__version": "2.0.15"
}`

So if you install the datatypes you could first try to get the datatype by name and if null install it?

**Comment by mattbrailsford** [comment]
I don't think this is the case. The unique identifier it refers to is the ID / UDI. Umbraco deploy is just telling you the friendly name so you know which one it relates to.

Also, TC checking for the existence of the data type wouldn't work because for TC, which runs first, is it won't exist and so it creates it. But then Umbraco deploy runs and then the data type now exists but conflicts, hence this problem.

**Comment by FransdeJong** [comment]
The phrasing of the error is a bit misleading than...

**Comment by tormnator** [comment]
Just ran into the same issue when cloning a Dev cloud instance onto a new Local installation. We should come up with a set of steps to work around the problem until a permanent solution is created. I'll see what I find out today, but maybe someone already have done it, and have the work around documented?

**Comment by Matthew-Wise** [comment]
In my issue I link to a resolution once you hit the problem if that helps :)

**Comment by mattbrailsford** [comment]
Hey folks, I've had a look at a fix for this this morning which I've submitted as PR #89. Essentially I've swapped out using the DataTypes service to register the datatypes in favor of inserting directly into the database tables and giving the datatypes fixed IDs. 

I'm yet to test this, but I believe this should potentially do the trick.

I'm gonna close this issue, but if you have any further comments, or you fancy testing it, we can move the discussion over to the PR
